version: '3.9'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
      - ~/ssl/explorer.cert.pem:/etc/nginx/ssl/explorer.cert.pem
      - ~/ssl/explorer.key.pem:/etc/nginx/ssl/explorer.key.pem
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
      - 443:443
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
