version: '3.9'

services:
  redis-db:
    image: 'redis:alpine'
    container_name: redis-db
    command: redis-server
    volumes:
      - ./redis-data:/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
