version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 6.10.2
    links:
      - db:database
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: https://rpc.stratisevm.com/
      ETHEREUM_JSONRPC_TRACE_URL: https://rpc.stratievm.com/
      ETHEREUM_JSONRPC_WS_URL: wss://rpc.stratisevm.com/
      CHAIN_ID: '105105'

  nft_media_handler:
    depends_on:
      - backend
    extends:
      file: ./services/nft_media_handler.yml
      service: nft_media_handler
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 6.10.2

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
  
  sc-verifier:
    extends:
      file: ./services/smart-contract-verifier.yml
      service: smart-contract-verifier

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  coinsupply:
    extends:
      file: ./services/coinsupply.yml
      service: coinsupply

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
      - coinsupply
    extends:
      file: ./services/nginx.yml
      service: proxy
